### ISSUE TITLE
Features suggestion for user convenience

### ISSUE THREAD

**Issue by hvdinh16** [SBRG/escher-maps#2]
- Add 'save as image' function to ipython escher like 'save as svg' on escher.github.io
- Save settings like how on MS office you can save templates/themes.
- Fold change conparison doesn't work on non-positive values and display as 'no data'

**Comment by zakandrewking** [comment]
Moved to Escher issues: 

https://github.com/zakandrewking/escher/issues/155
https://github.com/zakandrewking/escher/issues/153
https://github.com/zakandrewking/escher/issues/127
